version: '2'
services:
  web:
    build: .
    command: npm run start-dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: //cassandra
  # postgres:
  #   image: postgres:9.6.2-alpine
  #   environment:
  #     POSTGRES_USER: todoapp
  #     POSTGRES_DB: todos
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    restart: always
  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:latest
    depends_on:
      - cassandra
    volumes:
      - ./src/main/resources/cassandra_schema.cql:/schema.cql
    command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
