version: '3'
services:
  web:
    build: .
    command: ['ls']
    command:
      ['/usr/app/wait-for-it.sh', 'cassandra:9042','-t','50', '--', 'npm', 'run', 'start-dev']
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - cassandra
    restart: on-failure
    environment: 
      CASSANDRA_SERVER: cassandra
    links:
      - cassandra
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - '9042:9042'
      - '9160:9160'
    restart: always
  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:latest
    depends_on:
      - cassandra
    volumes:
      - .:/usr/app/
    command: /bin/bash -c "sleep 30 && echo loading cassandra keyspace && cqlsh cassandra -f usr/app/schema.cql"
