version: '3'
services:
  web:
    build: .
    command: ['ls']
    command:
      ['/usr/app/wait-for-it.sh', 'cassandra:9042','-t','50', '--', 'npm', 'run', 'start-dev']
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - '3000:3000'
    restart: on-failure
    environment: 
      CASSANDRA_SERVER: cassandra
  cass_node_1:
    image: cassandra:latest
    container_name: cass_node_1
    networks:
      dc1ring: 
        ipv4_address: 172.30.0.2
    expose: 
      - 7000
      - 7001
      - 7199
      - 9042
      - 9142
    ports:
      - '9042:9042'
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2000M
        reservations:
          cpus: '0.25'
          memory: 2000M
  cass_node_2:
    image: cassandra:latest
    container_name: cass_node_2
    networks:
      dc1ring: 
        ipv4_address: 172.30.0.3
    expose: 
      - 7000
      - 7001
      - 7199
      - 9042
      - 9142
    ports:
      - '9043:9042'
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2000M
        reservations:
          cpus: '0.25'
          memory: 2000M
networks:
  dc1ring:
      ipam:
          driver: default
          config:
              - subnet: 172.30.0.0/16